spring:
  application:
    name: darackbang-back-user

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.231:1521:xe
    username: darackbangadmin
    password: darackbangadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.orm.hibernate5.SpringJtaPlatform
        format_sql: true
        dialect: org.hibernate.community.dialect.OracleLegacyDialect
    show-sql: true

logging:
  level:
    root: info
    com.lab.darackbang.*: trace
    org.springframework.security.web : trace

com:
  lab:
    upload:
      path: C:\darackbang\upload
    eventUpload:
      path: C:\darackbang\upload\event

iamport:
  key: 3545062336248167
  secret: o1KReyEMGtrVKNPfaBhyDe6vTCAcds2tylDEjaQ4kYk8EB74wXuxmoSdzuMJY956IWkvUPTisHufkiPu
